<div id="pf21d" class="pf w0 h0" data-page-no="21d"><div class="pc pc21d w0 h0"><img class="bi x13 y5 w2 ha" alt="" src="bg21d.png"/><div class="t m0 xd h9 y75 ff1 fs3 fc0 sc0 lsb">《<span class="ff2 ls0 wsce">Python Co<span class="_ _6"></span>okb<span class="_ _6"></span>o<span class="_ _6"></span>ok</span><span class="ls0 wsa0">》第三版<span class="ff2 wsce">, Release 2.0.0</span></span></div><div class="t m0 x5 hf y3487 ff8 fs5 fc0 sc0 ls0">try:</div><div class="t m0 x3c hf y3488 ff8 fs5 fc0 sc0 ls0">...</div><div class="t m0 x5 hf y3489 ff8 fs5 fc0 sc0 ls0 ws4">except SomeException as e:</div><div class="t m0 x3c hf y348a ff8 fs5 fc0 sc0 ls0 ws4">raise DifferentException() from e</div><div class="t m0 x0 h9 y13a3 ff1 fs3 fc0 sc0 ls56 ws1fa">这样做的原因是你应该显示的将原因链接起来<span class="_ _c"></span>。也就是说<span class="_ _1"></span>，<span class="ff6 ls0">DifferentException</span></div><div class="t m0 x5 h9 ya86 ff1 fs3 fc0 sc0 ls0 ws14">是直接从 <span class="ff6 ws317">SomeException </span>衍生而来。这种关系可以从回溯结果中看出来。</div><div class="t m0 x0 h9 y25f9 ff1 fs3 fc0 sc0 ls3a ws153">如果你像下面这样写代码，你仍然会得到一个链接异常，不过这个并没有很清晰的</div><div class="t m0 x5 h9 y348b ff1 fs3 fc0 sc0 ls0">说明这个异常链到底是内部异常还是某个未知的编程错误。</div><div class="t m0 x5 hf y348c ff7 fs5 fca sc0 ls0 ws156">try<span class="ff8 fc0">:</span></div><div class="t m0 x3c hf y348d ff8 fs5 fc6 sc0 ls34 ws76a">...</div><div class="t m0 x5 hf y2afc ff7 fs5 fca sc0 ls0 ws146">except <span class="ff8 fc0">SomeException:</span></div><div class="t m0 x3c hf y348e ff7 fs5 fca sc0 ls0 ws83b">raise <span class="ff8 fc0">DifferentException()</span></div><div class="t m0 x0 h9 y198a ff1 fs3 fc0 sc0 ls0 wsc">当你使用 <span class="ff6 ws17c">raise<span class="_ _11"> </span>from </span>语句的话，就很清楚的表明抛出的是第二个异常。</div><div class="t m0 x0 h9 y348f ff1 fs3 fc0 sc0 ls3a ws153">最后一个例子中隐藏异常链信息。尽管隐藏异常链信息不利于回溯，同时它也丢失</div><div class="t m0 x5 h9 y3490 ff1 fs3 fc0 sc0 ls0">了很多有用的调试信息。不过万事皆平等，有时候只保留适当的信息也是很有用的。</div><div class="t m0 x5 hd y15e3 ff2 fs4 fc4 sc0 ls0 wsd91">16.10<span class="_ _e"> </span>14.10 <span class="ff1">重新抛出被捕获的异常</span></div><div class="t m0 x5 he y3491 ff2 fs2 fc4 sc0 ls0 wsadf">16.10.1 <span class="ff1">问题</span></div><div class="t m0 x0 h9 y1c83 ff1 fs3 fc0 sc0 ls0 wsc">你在一个 <span class="ff6 ws25d">except </span>块中捕获了一个异常，现在想重新抛出它。</div><div class="t m0 x5 he y3492 ff2 fs2 fc4 sc0 ls0 wsadf">16.10.2 <span class="ff1">解决方案</span></div><div class="t m0 x0 h9 y33b7 ff1 fs3 fc0 sc0 ls0 wsc">简单的使用一个单独的 <span class="ff6 ws19e">rasie </span>语句即可，例如：</div><div class="t m0 x5 hf y3493 ff7 fs5 fc5 sc0 ls0 ws139">&gt;&gt;&gt; <span class="fca">def <span class="ff8 fcb ws13a">example<span class="fc0">():</span></span></span></div><div class="t m0 x5 hf y3494 ff7 fs5 fc5 sc0 ls0 ws1a2">... <span class="fca ws156">try<span class="ff8 fc0">:</span></span></div><div class="t m0 x5 hf y3495 ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="ff8 fca ws13a">int<span class="fc0 ls34">(</span><span class="ff9 fc9 ws13b">&apos;</span><span class="fc9">N/A<span class="ff9 ls34">&apos;</span><span class="fc0">)</span></span></span></div><div class="t m0 x5 hf y3496 ff7 fs5 fc5 sc0 ls0 ws1a2">... <span class="fca ws146">except <span class="ff8 ws13a">ValueError<span class="fc0">:</span></span></span></div><div class="t m0 x5 hf y3497 ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="fca ws156">print<span class="ff8 fc0 ls34">(<span class="fc9 ls0 ws13a">&quot;Didn<span class="ff9 ws13b">&apos;</span><span class="ws4">t work&quot;<span class="fc0">)</span></span></span></span></span></div><div class="t m0 x5 h10 y3498 ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="fca">raise</span></div><div class="t m0 x5 h10 y3499 ff7 fs5 fc5 sc0 ls0">...</div><div class="t m0 x5 hf y349a ff7 fs5 fc5 sc0 ls0 ws139">&gt;&gt;&gt; <span class="ff8 fc0">example()</span></div><div class="t m0 x5 hf y349b ff8 fs5 fc8 sc0 ls0 ws13a">Didn<span class="ff9 ls34">&apos;</span><span class="ws13b">t work</span></div><div class="t m0 x5 hf y349c ff8 fs5 fce sc0 ls0 ws4">Traceback (most recent call last):</div><div class="t m0 x19 hf y349d ff8 fs5 fc0 sc0 ls0 ws13c">File <span class="fca ws13a">&quot;&lt;stdin&gt;&quot;</span><span class="ws13b">, line <span class="fc7 ws13a">1</span><span class="ws4">, in &lt;module&gt;</span></span></div><div class="t m0 x19 hf y349e ff8 fs5 fc0 sc0 ls0 ws13c">File <span class="fca ws13a">&quot;&lt;stdin&gt;&quot;</span><span class="ws13b">, line <span class="fc7 ws13a">3</span><span class="ws4">, in example</span></span></div><div class="t m0 x5 hf y349f ff8 fs5 fc2 sc0 ls0 ws13a">ValueError<span class="fc0 ws4">: invalid literal for int() with base 10: <span class="ff9 ls34">&apos;</span><span class="ws13a">N/A<span class="ff9">&apos;</span></span></span></div><div class="t m0 x5 hf y34a0 ff8 fs5 fc8 sc0 ls0">&gt;&gt;&gt;</div><div class="t m0 x5 h9 y29 ff2 fs3 fc0 sc0 ls0 wsd97">16.10.<span class="_ _36"> </span>14.10 <span class="ff1 wsd98">重新抛出被捕获的异常 </span>532</div></div><div class="pi" data-data='{"ctm":[1.500000,0.000000,0.000000,1.500000,0.000000,0.000000]}'></div></div>
