<div id="pf21c" class="pf w0 h0" data-page-no="21c"><div class="pc pc21c w0 h0"><img class="bi x13 y5 w2 ha" alt="" src="bg21c.png"/><div class="t m0 xd h9 y75 ff1 fs3 fc0 sc0 lsb">《<span class="ff2 ls0 wsce">Python Co<span class="_ _6"></span>okb<span class="_ _6"></span>o<span class="_ _6"></span>ok</span><span class="ls0 wsa0">》第三版<span class="ff2 wsce">, Release 2.0.0</span></span></div><div class="t m0 x15 hf y181 ff7 fs5 fca sc0 ls0 ws157">if <span class="ff8 fc0 ls34">e<span class="fc6">.</span><span class="ls0">__cause__:</span></span></div><div class="t m0 x16 hf y182 ff7 fs5 fca sc0 ls0 ws156">print<span class="ff8 fc0 ls34">(<span class="ff9 fc9">&apos;<span class="ff8 ls0 ws13a">Cause:</span>&apos;</span><span class="ls0 ws13b">, e</span><span class="fc6">.</span><span class="ls0">__cause__)</span></span></div><div class="t m0 x0 h9 y3469 ff1 fs3 fc0 sc0 ls0 ws12e1">当<span class="_ _6"></span>在 <span class="ff6 ws12e2">except </span><span class="ls19a wsc40">块中又有另外的异常被抛出时会导致一个隐藏的异常链的出现<span class="_ _c"></span>。例<span class="_ _1"></span></span></div><div class="t m0 x5 h9 y346a ff1 fs3 fc0 sc0 ls0">如：</div><div class="t m0 x5 hf y346b ff7 fs5 fc5 sc0 ls0 ws139">&gt;&gt;&gt; <span class="fca">def <span class="ff8 fcb ws13a">example2<span class="fc0">():</span></span></span></div><div class="t m0 x5 hf y346c ff7 fs5 fc5 sc0 ls0 ws1a2">... <span class="fca ws156">try<span class="ff8 fc0">:</span></span></div><div class="t m0 x5 hf y346d ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="ff8 fca ws13a">int<span class="fc0 ls34">(</span><span class="ff9 fc9 ws13b">&apos;</span><span class="fc9">N/A<span class="ff9 ls34">&apos;</span><span class="fc0">)</span></span></span></div><div class="t m0 x5 hf y1f88 ff7 fs5 fc5 sc0 ls0 ws1a2">... <span class="fca ws146">except <span class="ff8 ws2a3">ValueError </span><span class="ws157">as <span class="ff8 fc0">e:</span></span></span></div><div class="t m0 x5 hf y1f89 ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="fca ws156">print<span class="ff8 fc0 ls34">(<span class="fc9 ls0 ws13a">&quot;Couldn<span class="ff9 ls34">&apos;</span><span class="ws13b">t parse:&quot;<span class="fc0 ws4">, err)</span></span></span></span></span></div><div class="t m0 x5 h10 y346e ff7 fs5 fc5 sc0 ls0">...</div><div class="t m0 x5 hf y346f ff8 fs5 fc8 sc0 ls0">&gt;&gt;&gt;</div><div class="t m0 x5 hf y3470 ff7 fs5 fc5 sc0 ls0 ws139">&gt;&gt;&gt; <span class="ff8 fc0">example2()</span></div><div class="t m0 x5 hf y3471 ff8 fs5 fce sc0 ls0 ws4">Traceback (most recent call last):</div><div class="t m0 x19 hf y3472 ff8 fs5 fc0 sc0 ls0 ws13c">File <span class="fca ws13a">&quot;&lt;stdin&gt;&quot;</span><span class="ws13b">, line <span class="fc7 ws13a">3</span><span class="ws4">, in example2</span></span></div><div class="t m0 x5 hf y3473 ff8 fs5 fc2 sc0 ls0 ws13a">ValueError<span class="fc0 ws4">: invalid literal for int() with base 10: <span class="ff9 ls34">&apos;</span><span class="ws13a">N/A<span class="ff9">&apos;</span></span></span></div><div class="t m0 x0 h9 y3474 ff1 fs3 fc0 sc0 ls0">在处理上述异常的时候，另外一个异常发生了：</div><div class="t m0 x5 hf y3475 ff8 fs5 fc0 sc0 ls0 ws4">Traceback (most recent call last):</div><div class="t m0 x19 hf y3476 ff8 fs5 fc0 sc0 ls0 ws4">File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;</div><div class="t m0 x19 hf y296e ff8 fs5 fc0 sc0 ls0 ws4">File &quot;&lt;stdin&gt;&quot;, line 5, in example2</div><div class="t m0 x5 hf y3477 ff8 fs5 fc0 sc0 ls0 ws4">NameError: global name <span class="ff9 ws13b">&apos;</span><span class="ws13a">err<span class="ff9 ls32">&apos;</span></span>is not defined</div><div class="t m0 x5 hf y3478 ff8 fs5 fc0 sc0 ls0">&gt;&gt;&gt;</div><div class="t m0 x0 h9 y3479 ff1 fs3 fc0 sc0 ls139 ws859">这个例子中<span class="_ _d"></span>，<span class="_ _6"></span>你同时获得了两个异常的信息<span class="_ _d"></span>，但是对异常的解释不同<span class="_ _c"></span>。这时候<span class="_ _c"></span>，<span class="_ _c"></span></div><div class="t m0 x5 h9 y347a ff6 fs3 fc0 sc0 ls0 ws1d1">NameError <span class="ff1">异常被作为程序最终异常被抛出，而不是位于解析异常的直接回应中。</span></div><div class="t m0 x0 h7 y6a1 ff1 fs3 fc0 sc0 ls0 ws38">如果，你想忽略掉异常链，可使用 <span class="ff6 ws4">raise from None<span class="_ _16"> </span><span class="ff4">:</span></span></div><div class="t m0 x5 hf y347b ff7 fs5 fc5 sc0 ls0 ws139">&gt;&gt;&gt; <span class="fca">def <span class="ff8 fcb ws13a">example3<span class="fc0">():</span></span></span></div><div class="t m0 x5 hf y347c ff7 fs5 fc5 sc0 ls0 ws1a2">... <span class="fca ws156">try<span class="ff8 fc0">:</span></span></div><div class="t m0 x5 hf y2a6 ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="ff8 fca ws13a">int<span class="fc0 ls34">(</span><span class="ff9 fc9 ws13b">&apos;</span><span class="fc9">N/A<span class="ff9 ls34">&apos;</span><span class="fc0">)</span></span></span></div><div class="t m0 x5 hf y347d ff7 fs5 fc5 sc0 ls0 ws1a2">... <span class="fca ws146">except <span class="ff8 ws13a">ValueError<span class="fc0">:</span></span></span></div><div class="t m0 x5 hf y347e ff7 fs5 fc5 sc0 ls0 ws8e2">... <span class="fca ws16a">raise <span class="ff8 ws13a">RuntimeError<span class="fc0">(<span class="ff9 fc9 ls34">&apos;</span><span class="fc9 ws4">A parsing error occurred<span class="ff9 ws13b">&apos;</span></span><span class="ls33">)</span></span></span><span class="ws218">from <span class="ff8 ws13a">None<span class="fc6 ls34 ws76a">...</span></span></span></span></div><div class="t m0 x5 hf y273b ff8 fs5 fc8 sc0 ls0">&gt;&gt;&gt;</div><div class="t m0 x5 hf y347f ff8 fs5 fc8 sc0 ls0">example3()</div><div class="t m0 x5 hf y3480 ff8 fs5 fce sc0 ls0 ws4">Traceback (most recent call last):</div><div class="t m0 x19 hf y3481 ff8 fs5 fc0 sc0 ls0 ws13c">File <span class="fca ws13a">&quot;&lt;stdin&gt;&quot;</span><span class="ws13b">, line <span class="fc7 ws13a">1</span><span class="ws4">, in &lt;module&gt;</span></span></div><div class="t m0 x19 hf y986 ff8 fs5 fc0 sc0 ls0 ws13c">File <span class="fca ws13a">&quot;&lt;stdin&gt;&quot;</span><span class="ws13b">, line <span class="fc7 ws13a">5</span><span class="ws4">, in example3</span></span></div><div class="t m0 x5 hf y3482 ff8 fs5 fc2 sc0 ls0 ws13a">RuntimeError<span class="fc0 ws4">: A parsing error occurred</span></div><div class="t m0 x5 hf y3483 ff8 fs5 fc8 sc0 ls0">&gt;&gt;&gt;</div><div class="t m0 x5 he y3484 ff2 fs2 fc4 sc0 ls0 ws212">16.9.3 <span class="ff1">讨论</span></div><div class="t m0 x0 h9 y1a16 ff1 fs3 fc0 sc0 ls0 ws12e3">在设计代码时，在<span class="_ _6"></span>另外一个 <span class="ff6 ws61a">except </span><span class="ws12e4">代码块中使<span class="_ _6"></span>用 <span class="ff6 ws12e5">raise </span><span class="wsa0">语句的时候你要<span class="_ _6"></span>特别小心</span></span></div><div class="t m0 x5 h9 y3485 ff1 fs3 fc0 sc0 ls0 ws12e6">了。<span class="_ _6"></span>大多<span class="_ _6"></span>数<span class="_ _6"></span>情<span class="_ _6"></span>况<span class="_ _6"></span>下，<span class="_ _6"></span>这<span class="_ _6"></span>种 <span class="ff6 ws2b7">raise </span><span class="ls1e ws12e7">语句都应该被改成 </span><span class="ff6 ws12e8">raise<span class="_ _23"> </span>from </span><span class="wsa0">语<span class="_ _6"></span>句。<span class="_ _6"></span>也<span class="_ _6"></span>就<span class="_ _6"></span>是说<span class="_ _6"></span>你<span class="_ _6"></span>应</span></div><div class="t m0 x5 h9 y3486 ff1 fs3 fc0 sc0 ls0">该使用下面这种形式：</div><div class="t m0 x5 h9 y29 ff2 fs3 fc0 sc0 ls0 ws21d">16.9.<span class="_ _36"> </span>14.9 <span class="ff1 ws98a">捕获异常后抛出另外的异常 </span>531</div></div><div class="pi" data-data='{"ctm":[1.500000,0.000000,0.000000,1.500000,0.000000,0.000000]}'></div></div>
